name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      # Yeh action runner par custom Gradle distribution environment allocate kar dega

    - name: Initialize Missing Gradle Wrapper
      run: |
        # Agar gradlew nahi hai, to system gradle se wrapper generate karein
        gradle wrapper --gradle-version 8.2
        chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Generated APK
      uses: actions/upload-artifact@v4
      with:
        name: Cyber-Booster-Debug-APK
        path: "**/build/outputs/apk/debug/*-debug.apk"
        
